### ISSUE TITLE
Add music source

### ISSUE THREAD

**Issue by ngovil21** [ngovil21/RequestChannel.bundle#4]
Search for music on MusicBrainz, Discog, or Last.Fm  

Possibly integrate with Headphones for automation.

**Comment by guru69** [comment]
If you need help testing this let me know. I have a local headphones and Musicbrainz mirror servers.

**Comment by ngovil21** [comment]
I will let you know when I start working on this. Currently it's on the backburner because I don't use it personally and it'll be a more involved update.

**Comment by bigbigspoon** [comment]
I came here to request this as well. Adding Headphones would compliment the channel perfectly! Thank you for all your work on this @ngovil21 !

**Comment by UdinRex** [comment]
Great work, and I second the need for headphones!

**Comment by ngovil21** [comment]
So this is very late, but I have added this feature in the development branch. Would anyone like to test it for me? I only plan to add album support, because I think adding artist support would be a much, and searching for tracks is a little more tedious. 

I do not plan to add any of the management features for headphones, but hopefully this satisfies most of you.

**Comment by UdinRex** [comment]
Best news. Will get to testing!

**Comment by ngovil21** [comment]
added in 2a76749c1c34e0882a979ec8c1efffaf635b50dd
