### ISSUE TITLE
Slack Notifications

### ISSUE THREAD

**Issue by wabit** [ngovil21/RequestChannel.bundle#41]
I have recently moved away from puchbullet and the like the a Slack channel.

It would be great if updates/notifications could be pushed into a channel

**Comment by flixajki** [comment]
Great suggestion especially since the same one can be using for discord too just by adding /slack at the end of discord webhook.

**Comment by haxcop** [comment]
@wabit I'm totally agree with you I've just moved from pushbullet besides the fact that is not working properly anymore with the different tools, @ngovil21 any-Idea when can this be added?. 
Kind regards, 
HAxcop

**Comment by ngovil21** [comment]
Added here c8a1856f84468f0542c957221dead3065ef166f9
