### ISSUE TITLE
Remove request after completed

### ISSUE THREAD

**Issue by garlandkr** [ngovil21/RequestChannel.bundle#45]
I'm not sure if I have the latest version and maybe this has already been implemented, but my current version does not clear requests after they are available in plex.

**Comment by ngovil21** [comment]
Not completely automated, but you can now clear movie requests that have been marked as done by Couchpotato or Radarr. Added in d224c598308a41be33041ddeaa09485b837e6a64

**Comment by ngovil21** [comment]
This was added in 9bd904aaafe7bb971fb1675f35f5637469f28883.

Closing issue.
