### ISSUE TITLE
Date+Time of a request

### ISSUE THREAD

**Issue by acherubino** [ngovil21/RequestChannel.bundle#50]
Hi, would it be possible to add support so that when a user requests something it stores the date and time of when it was requested? Something like how when requests are viewed it shows the user who requested it. Maybe also be able to sort the requests by when they were requested. I have a lot of active users and I like to fill requests in the order that they come in.

**Comment by ngovil21** [comment]
I'll add this option in at some point, but it will lower on the list. If you get notifications it would probably be easier to sort those. When this feature is added, it will only work with requests added after the update.

**Comment by ngovil21** [comment]
Added in d224c598308a41be33041ddeaa09485b837e6a64

You will need to go to Manage Channel and click on Sort requests by name, so that it says sort by time and requests will be sorted. Also in clients that allow you to see the Details view, the time requested will be at the end of the summary.
