### ISSUE TITLE
Feature Request - Radarr Support

### ISSUE THREAD

**Issue by borFSU** [ngovil21/RequestChannel.bundle#51]
Love the channel. I just switched from CP to Radarr, which is a fork from Sonarr to grab movies. Would love to see it incorporated into the channel. I imagine it would be very similar to Sonarr implementation.  Again, great work. Thanks

**Comment by borFSU** [comment]
Sorry if this is the wrong place for this. I wasn't sure where else to put it.

**Comment by ngovil21** [comment]
Radarr support added in 47550180e04dfc4738bc848ce62d48220e209e92
