### ISSUE TITLE
Pushbullet SSLContext Failure in v0.8.2

### ISSUE THREAD

**Issue by rsgabriel** [ngovil21/RequestChannel.bundle#54]
File "R:\Plex\Plex Media Server\Plug-ins\PlexRequestChannel.bundle\Contents\Code\Session.py", line 2791, in notifyRequest
    summary = ""
  File "R:\Plex\Plex Media Server\Plug-ins\PlexRequestChannel.bundle\Contents\Code\Session.py", line 2851, in sendPushBullet
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
AttributeError: 'module' object has no attribute 'SSLContext'

2017-02-16 10:18:33,551 (81d0) :  DEBUG (logkit:13) - Pushbullet failed: 'module' object has no attribute 'SSLContext'

Running Plex in IIS HTTPS with a valid LetsEncrypt cert. Python version 2.7.12

**Comment by ngovil21** [comment]
Plex actually has it's own version of Python bundled with the server. For some reason the windows version doesn't have the required ssl library. Don't know of another way to do this.

**Comment by rsgabriel** [comment]
The startup shortcut I use for PlexPy specifically uses the 2.7.12 version:

C:\Python27\python.exe c:\plexpy\plexpy.py

**Comment by rsgabriel** [comment]
SSLContext required 2.7.9 i believe

Should i disable SSL on plex to avoid this? or is there no way around this issue at all on windows?

**Comment by ngovil21** [comment]
Ya there is currently no workaround. The python version for plex channels is separate from what you install. Disabling SSL would not work.

I'll keep looking into it and let you know if I figure anything out.

**Comment by rsgabriel** [comment]
So this issue seems fixed in the latest version of Plex, I was running an older version and after updating plex  the pushbullet notifications from this channel began working again.
