### ISSUE TITLE
No results being returned in search

### ISSUE THREAD

**Issue by nexxai** [ngovil21/RequestChannel.bundle#62]
I'm sure this is probably a me-issue (because I'd expect many more people to be reporting this problem if it wasn't) but all of a sudden, searching doesn't return any results.

The problem started earlier this week, and I had not made *any* changes to the server whatsoever which may have affected things.  I did upgrade to the latest version of the channel to make sure it wasn't an old version causing issues, but that made no change.

Is there a log file or anything that I can look through to see if I can narrow down the problem?

**Comment by nexxai** [comment]
Well of course, I leave a GitHub issue and the problem goes away on its own.

**Comment by ngovil21** [comment]
Likely due to the movie database used was down for that interval. For future references I just made a wiki page on channel logs: https://github.com/ngovil21/RequestChannel.bundle/wiki/How-to-get-Channel-Log
