### ISSUE TITLE
Requests can be made, but do not auto-send to CP.  Sending manually will work.

### ISSUE THREAD

**Issue by iStatiK** [ngovil21/RequestChannel.bundle#63]
Running Debian 8 with everything in it's own Docker Container.  Minus PR, as I have the channel installed.
In the PlexRequest Channel, CP is set to http://127.0.0.1:5050 along with API and auto-add to CP is enabled.
I am not sure where the issue is.  If it is a CP or PR issue.
Attached is the latest log from the PMS Plugin Logs folder.  I removed all previous requests and sent a new request, so this log will reflect the entire process of requesting.
Please let me know if you need anything else.

[com.plexapp.plugins.plexrequestschannel.txt](https://github.com/ngovil21/RequestChannel.bundle/files/1098237/com.plexapp.plugins.plexrequestschannel.txt)

**Comment by ngovil21** [comment]
Glad you were able to switch to Radarr, but this was a bug. I will fix the bug and upload it to the master branch after testing.
