### ISSUE TITLE
Alternate Keyboard allows user to see requests even if disabled

### ISSUE THREAD

**Issue by ds8k** [ngovil21/RequestChannel.bundle#65]
If a user is using iOS (and thus using the alternate keyboard input) they're able to see all the options I have disabled and even manage requests. This also happens if using the channel in a web browser.

If they switch to device keyboard, the channel looks correct.

**Comment by ngovil21** [comment]
That is strange. I don't have an iOS device to test with, could you go to Manage Channel and make sure "Debug" is set to on and send me the log after a client with iOS logs in? My email is ngovil21@gmail.com.

Thanks.

**Comment by ds8k** [comment]
Email sent.

For what it's worth, this is how I installed the channel:

```
fetch -o master.zip https://github.com/ngovil21/RequestChannel.bundle/archive/master.zip
unzip master.zip
mv RequestChannel.bundle-master/ RequestChannel.bundle/
chown -R plex:plex RequestChannel.bundle/
chmod -R 755 RequestChannel.bundle/
```

**Comment by ngovil21** [comment]
Ok thanks, I see what you are saying. I will post a fix.

**Comment by ngovil21** [comment]
Merged fixes to the `master` branch. Please update and check now.

**Comment by ds8k** [comment]
All fixed! Thank you
