### ISSUE TITLE
Where does the presets get saved?

### ISSUE THREAD

**Issue by bsollenb54** [ngovil21/RequestChannel.bundle#66]
Where are the presets/config getting saved? I've spun up two requestchannel.bundles (one to request kids movies and one for the adults). I use Plex Pass with family settings, so even though it's redundant, I have sickrage and couchpotato download TVs/movies to a different drive from where Sonarr and Radarr download TV/movies to.

Anyway, the issue I'm running into is the two instances of plex request settings' overwrite each others. Likely because they're pointing to the same config file path? I'm just guessing, but any idea how I can modify one of my bundles to point somewhere else for a config file path?

Thanks!

**Comment by ngovil21** [comment]
Unfortunately this is not possible unless you change the code to give the channels different names in Code\init.py. That's just how Plex works with channels.

**Comment by bsollenb54** [comment]
So is it just as simple as changing the title = 'Request Channel' to something else in code\init.py so that Plex creates a different saved presets or user data file?

It's an easy question that I'd check myself but traveling for work this week and not near my server. Thanks!

**Comment by ngovil21** [comment]
I would change the `TITLE` and `PREFIX` to different things which are at the top of` __init__.py` and in `Session.py`.
