### ISSUE TITLE
Couchpotato

### ISSUE THREAD

**Issue by jfairham1** [ngovil21/RequestChannel.bundle#68]
I seem to have issues connecting through to couchpotato. 
I have the url base set as couchpotato. (in couchpotato)

In plex requests channel i'm setting as http://127.0.0.1:5050/couchpotato

API is entered in plex requests channel, 
When I try and connect through manage couchpotato or send a request, i'm getting error loading couchpotato message. 

I've tried with Sonarr, with the base url and this works fine, so somewhat stumped on this one.

**Comment by ngovil21** [comment]
Please send the channel log to ngovil21@gmail.com. Information on where to find the channel log can be found on the wiki.

**Comment by bigeazy000** [comment]
I'm seeing the same thing with Couchpotato, Sonarr is working fine. I'll send you my logs.

**Comment by ngovil21** [comment]
Ok guys, try updating the channel, had an update in the pipeline for a while, but just pushed it to the master branch.

**Comment by bigeazy000** [comment]
I will try to give it a shot when I have a chance. I wound up switching to Radarr and I don't think I will look back.. Thanks for the update!

**Comment by jfairham1** [comment]
I did the same switching to radarr and the requests channel works fine with it.
