### ISSUE TITLE
channel doesn't work properly on android smartphones/tablet (App)

### ISSUE THREAD

**Issue by pluusla** [ngovil21/RequestChannel.bundle#69]
Hi there!

I'm facing an error/issue with the channel:
I set the preference for monitor seasons on manual. This works fine on plex online. But if I want to add a tv show on my android smartphone (via the app), I never see the season choose menu.

Online: New TV-Request -> Show-Name -> Add Yes -> Selecting Shows

Android: New TV-Request -> Show-Name -> Add Yes -> Main menu shows up.

Is this really an issue or did I just something wrong? ;)

Thanks.

**Comment by ngovil21** [comment]
yes it's an issue that has been reported but I wasn't able to fix it before. Will merge the issues and take a look again sometime.

#42
