### ISSUE TITLE
Not working with other base url

### ISSUE THREAD

**Issue by drtomasso** [ngovil21/RequestChannel.bundle#71]
Using Radarr, with base url `/radarr`, I've added this to settings `http://127.0.0.1:7878/radarr/`. The logs shows a request made for `http://127.0.0.1:7878/api/Profile` and not `http://127.0.0.1:7878/radarr/api/Profile`

Am I doing something wrong?

**Comment by ngovil21** [comment]
After saving the settings, please try refreshing the channel page, or restarting your Plex Server if possible. If that doesn't fix the issue, please email me the log to ngovil21@gmail.com with a picture of the Request Channel Settings (please remove or censor the api key).

**Comment by drtomasso** [comment]
Restarting Plex server solved the issue
