### ISSUE TITLE
Everything added to Sonarr or Radarr is added as unmonitored

### ISSUE THREAD

**Issue by MrDemocracy** [ngovil21/RequestChannel.bundle#79]
When I, or someone else using my server adds something to radarr or sonarr, it's added as "unmonitored". This makes it impossible for things to be downloaded automatically. I always have to re-monitor everything recently added periodically.

**Comment by ngovil21** [comment]
What do you have set for `Monitor Seasons` under Sonarr settings of the channel?

And do you have `Search for Movie after add` enabled in your Radarr settings of the channel?

**Comment by MrDemocracy** [comment]
> What do you have set for `Monitor Seasons` under Sonarr settings of the channel?

Okay, that's why...Thanks 👍
